In [2]:
import pandas as pd

In [3]:
implicit = pd.read_csv('./datasets_recsys/implicit_ndcg_story_results_books.csv', sep=',', encoding='latin')
random = pd.read_csv('./datasets_recsys/ndcg_results__stories_random_books.csv', sep=',', encoding='latin')
popular = pd.read_csv('./datasets_recsys/ndcg__stories_results_popular_books.csv', sep=',', encoding='latin')

In [4]:
implicit[['ndcg@5', 'precision@5', 'MAP']].describe()

            ndcg@5  precision@5          MAP
count  1000.000000  1000.000000  1000.000000
mean      0.313650     0.122200     0.138313
std       0.367536     0.149698     0.212689
min       0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000
50%       0.000000     0.000000     0.000000
75%       0.630930     0.200000     0.270833
max       1.000000     0.800000     0.937500

In [5]:
random[['ndcg@5', 'precision@5', 'MAP']].describe()

            ndcg@5  precision@5          MAP
count  1000.000000  1000.000000  1000.000000
mean      0.004000     0.001600     0.001667
std       0.049865     0.019946     0.027428
min       0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000
50%       0.000000     0.000000     0.000000
75%       0.000000     0.000000     0.000000
max       1.000000     0.400000     0.791667

In [6]:
popular[['ndcg@5', 'precision@5', 'MAP']].describe()

            ndcg@5  precision@5          MAP
count  1000.000000  1000.000000  1000.000000
mean      0.013992     0.003400     0.006562
std       0.111066     0.025867     0.055578
min       0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000
50%       0.000000     0.000000     0.000000
75%       0.000000     0.000000     0.000000
max       1.000000     0.200000     0.520833